config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'horse_race#index'
  get 'horse_race/race_list'
  get 'horse_race/horse_list'
  put 'horse_race/horse_list', to: 'horse_race#save_forecast'

  # logout
  devise_scope :user do
    get 'sign_out', to: "sessions#destroy"
  end

  namespace :api do
    resources :posts, :users
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/horse_race_controller.rb
class HorseRaceController < ApplicationController
  require 'uri'
  require 'date'
  require_relative './../helpers/netkeiba_scraper'

  # flag for display combobox
  @exists_forecast

  # root page #
  def index
    get_race_header()
  end

  # rase list page #
  def race_list()
    target = params[:target]
    @date = params[:date]
    get_race_header()
    get_race_list(target)
  end

  helper_method :is_registered_forecast

  # horse list page #
  def horse_list()
    @date = params[:date]
    get_race_list(params[:target_date])
    get_race_info(adjust_target(params[:target]))
    get_forecast
  end

  def adjust_target(target)
    target = target.gsub("race_old", "race")
    target = target << "&mode=shutuba"
    return target
  end

  def get_forecast()
    if current_user
      @my_forecasts = Forecast.where("race_id = ? AND user_id = ?", get_race_id, get_user_id)
      @other_users = Forecast.where("race_id = ? AND user_id != ?", get_race_id, get_user_id)
                             .joins("INNER JOIN users ON forecasts.user_id = users.id")
                             .select("forecasts.user_id, users.display_name").distinct
      @other_forecasts = Forecast.where("race_id = ? AND user_id != ?", get_race_id, get_user_id)
    else
      @other_users = Forecast.where("race_id = ?", get_race_id)
                             .joins("INNER JOIN users ON forecasts.user_id = users.id")
                             .select("forecasts.user_id, users.display_name").distinct
      @other_forecasts = Forecast.where("race_id = ?", get_race_id)
    end
  end

  def save_forecast()
    race_id = params[:race_id].to_i
    user_id = get_user_id
    horse_number = params[:horse_number].to_i
    forecast = params[:forecast].to_i

    current_forecast = find_forecast(race_id, user_id, horse_number)

    if current_forecast then
      if delete?(forecast) then
        return delete_forecast(current_forecast)
      end
      return update_forecast(current_forecast, forecast)
    end
    return create_forecast(race_id, user_id, horse_number, forecast)
  end

  def get_race_id
    adjust_target(params[:target]).split("&")[1][-12..-1].to_i
  end

  def get_user_id
    current_user.id
  end

  def find_forecast(race_id, user_id, horse_number)
    Forecast.find_by(race_id: race_id, user_id: user_id, horse_number: horse_number)
  end

  def create_forecast(race_id, user_id, horse_number, forecast)
    Forecast.create(user_id: user_id, race_id: race_id, horse_number: horse_number, forecast: forecast)
  end

  def update_forecast(current_forecast, forecast)
    current_forecast.update_attributes(forecast: forecast)
  end

  def delete_forecast(forecast)
    forecast.destroy
  end

  def delete?(forecast)
    forecast == 0
  end

end

app/helpers/horse_race_helper.rb
module HorseRaceHelper
end

app/views/horse_race/horse_list.html.slim
.main-content
  .today-race-list.panel.panel-info
    .panel-heading.align-center
      = @date
    .panel-body
      - @race_per_place_list.each do |race_per_place|
        .race-per-date
          p.race-count
            = race_per_place[:race_place_info][:date]
          - race_per_place[:race_list].each do |race|
            = link_to horse_race_horse_list_path(target: race.url, target_date: params[:target_date], date: params[:date]), class: race.get_race_button_class do
              = "#{race.get_race_number}R"
  .horse-list-header.panel.panel-info
    .panel-body
      p.header-race-date-age
        = @race_detail[:date_age]
      p.header-race-number
        = @race_detail[:number]
      p.header-race-name
        = @race_detail[:name]
      p.header-race-condition
        = @race_detail[:condition]
      = link_to 'netkeiba', "http://race.netkeiba.com#{params[:target]}", class: 'btn btn-default header-netkeiba-link', :target=>["_blank"]
  table.table.table-bordered.table-hover.table-striped.horse-table
    thead
      tr
        th.header.align-center
          | 枠
        th.header.align-center
          | 番
        th.header.align-center
          | 馬名
        th.header.align-center
          | 性
        th.header.align-center
          | 齢
        th.header.align-center
          | 斤
        th.header.align-center
          | 騎手
        th.header.align-center
          | 率
        th.header.align-center
          | 人
        - if user_signed_in?
          th.header.align-center
            | 予想
        - @other_users.each do |user|
          th.header.align-center
            = truncate(user[:display_name], :length => 3, :omission => '')
    tbody
      - forecast_select = { "-" => 0, "◎" => 1, "○" => 2, "▲" => 3, "△" => 4, "☆" => 5 }
      - forecast_mark = { 1 => "◎", 2 => "○", 3 => "▲", 4 => "△", 5 => "☆" }
      - @horse_list.each do |horse|
        tr
          td class=horse.get_gate_class
            = "#{horse.gate_number}"
          td.horse-table.horse-number.text-upright.background-white
            = "#{horse.horse_number}"
          td.horse-table.horse-name
            = "#{horse.name}"
          td class=horse.get_sex_class
            = "#{horse.sex}"
          td.horse-table.horse-age.text-upright
            = "#{horse.age}"
          td.horse-table.horse-handi.text-upright
            = "#{horse.handi}"
          td.horse-table.horse-jockey
            = "#{horse.jockey}"
          td.horse-table.horse-odds.text-upright
            = "#{horse.odds}"
          td.horse-table.horse-rank.text-upright
            = "#{horse.rank}"
          - if user_signed_in?
            td.horse-table.forecast
              - if horse.gate_number.nil? then
                - return
              - @exists_forecast = false
              - @my_forecasts.each do |forecast|
                - if forecast[:horse_number].to_i == horse.horse_number.to_i then
                  = select :forecast, :key, forecast_select, :selected => forecast[:forecast], class: 'select-mark'
                  - @exists_forecast = true
              - if @exists_forecast == false
                = select :forecast, :key, forecast_select, class: 'select-mark'
          - @other_users.each do |other_user|
            - other_forecasts = @other_forecasts.where("user_id = ?", other_user.user_id)
            td.horse-table.forecast
              - other_forecasts.each do |other_forecast|
                - if other_forecast[:horse_number].to_i == horse.horse_number.to_i then
                  = forecast_mark[other_forecast[:forecast]]
  #posts
    posts
  = javascript_pack_tag 'posts_vue'

app/views/horse_race/index.html.slim
.title-panel
  = image_tag 'title_001.jpg', class: 'title-image'
  .title-content
    p.title
      | tekkaba
    p.sub-title
      | ヨロコビを共有しよう
.contents-panel
  = image_tag 'contents_001.jpg', class: 'contents-image'
  .race-date-div
    p.date-header.align-center
      | 開催日一覧
    p.date-content.align-center
      - @race_header.each do |header|
        = link_to header[:date], horse_race_race_list_path(target: header[:url], date: header[:date]), class: 'btn btn-primary race-date-button'

app/views/horse_race/race_list.html.slim
.main-content
  .page-header.title-header
    h2.race-list-title
      = @date
  .race-date-div-wide.panel.panel-info
    .panel-heading.align-center
      | 開催日一覧
    .panel-body
      - @race_header.each do |header|
        = link_to header[:date], horse_race_race_list_path(target: header[:url], date: header[:date]), class: 'btn btn-primary race-date-button-wide'
  div
    - @race_per_place_list.each do |race_per_place|
      .race-per-place-div.panel.panel-default
        .panel-heading.align-center
          p.race-count
            = race_per_place[:race_place_info][:date]
          p.race-condition
            = race_per_place[:race_place_info][:condition]
        - race_per_place[:race_list].each do |race|
          .race-number-div.bg-primary
            p.race-number.align-center
              = "#{race.get_race_number}R"
          = link_to horse_race_horse_list_path(target: race.url, target_date: params[:target], date: params[:date]), class: race.get_race_button_class do
            = race.title
            br
            = race.detail